language: objective-c
xcode_workspace: Example/FormValidation.xcworkspace
xcode_scheme: FormValidation
xcode_sdk: iphonesimulator8.1

before_install: 
- brew update
- brew unlink xctool
- brew install xctool
