language: objective-c
xcode_workspace: Example/SPXDataValidators.xcworkspace
xcode_scheme: SPXDataValidators
xcode_sdk: iphonesimulator8.1

before_install: 
- brew update
- brew unlink xctool
- brew install xctool
